### ISSUE TITLE
Cant connect using ssh deployment method

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver-configurator#13]
This is the issue I'm getting on the latest version of master. Note: The error doesn't appear for the released version that comes with the opt-add-configurator option in btcpay. 

```
System.InvalidOperationException: Cannot get the value of a token type 'False' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.blockdevices[0].rm | LineNumber: 2 | BytePositionInLine: 50.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'False' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
```

I tried using: different browsers, hostname as domain & IP, existing settings checkbox enabled & disabled.

**Comment by Kukks** [comment]
can you run `lsblk --json` on the machine you tried to deploy to?

**Comment by britttttk** [comment]
> can you run `lsblk --json` on the machine you tried to deploy to?

```
{
   "blockdevices": [
      {"name":"loop0", "maj:min":"7:0", "rm":false, "size":"71.5M", "ro":true, "type":"loop", "mountpoint":"/snap/lxd/16740"},
      {"name":"loop1", "maj:min":"7:1", "rm":false, "size":"55.3M", "ro":true, "type":"loop", "mountpoint":"/snap/core18/1885"},
      {"name":"loop2", "maj:min":"7:2", "rm":false, "size":"70.6M", "ro":true, "type":"loop", "mountpoint":"/snap/lxd/16922"},
      {"name":"loop3", "maj:min":"7:3", "rm":false, "size":"31M", "ro":true, "type":"loop", "mountpoint":"/snap/snapd/9721"},
      {"name":"loop4", "maj:min":"7:4", "rm":false, "size":"30.3M", "ro":true, "type":"loop", "mountpoint":null},
      {"name":"loop5", "maj:min":"7:5", "rm":false, "size":"31M", "ro":true, "type":"loop", "mountpoint":"/snap/snapd/9607"},
      {"name":"sda", "maj:min":"8:0", "rm":false, "size":"500G", "ro":false, "type":"disk", "mountpoint":"/mnt/volume_tor1_01"},
      {"name":"vda", "maj:min":"252:0", "rm":false, "size":"50G", "ro":false, "type":"disk", "mountpoint":null,
         "children": [
            {"name":"vda1", "maj:min":"252:1", "rm":false, "size":"49.9G", "ro":false, "type":"part", "mountpoint":"/"},
            {"name":"vda14", "maj:min":"252:14", "rm":false, "size":"4M", "ro":false, "type":"part", "mountpoint":null},
            {"name":"vda15", "maj:min":"252:15", "rm":false, "size":"106M", "ro":false, "type":"part", "mountpoint":"/boot/efi"}
         ]
      }
   ]
}
```
