### ISSUE TITLE
Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/app/docker-fragments/opt-add-configurator.yml'

### ISSUE THREAD

**Issue by osilloh** [btcpayserver/btcpayserver-configurator#3]
Attempting manual install based on https://configurator.kukks.org web developed script.

Here is where it stopped. Apologies, I am a noob, a "Test Minion" if you will. Had to rebuild from a crashed BTCpayserver(I set aside that microSD and Flash drive, hoping it can be revived) so thought I would help test this out. I am on a Rpi4 4g, 64g microSD, 1TB SSD.

Generating /app/Generated/docker-compose.generated.yml

Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/app/docker-fragments/opt-add-configurator.yml'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at DockerGenerator.DockerComposeDefinition.ParseDocument(FragmentName fragment) in /source/DockerComposeDefinition.cs:line 273
   at DockerGenerator.DockerComposeDefinition.<>c__DisplayClass20_0.<Build>b__9(FragmentName f) in /source/DockerComposeDefinition.cs:line 72
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DockerGenerator.DockerComposeDefinition.Build() in /source/DockerComposeDefinition.cs:line 72
   at DockerGenerator.Program.Run(DockerComposition composition, String name, String output) in /source/Program.cs:line 88
   at DockerGenerator.Program.Main(String[] args) in /source/Program.cs:line 27
Failed to generate the docker-compose
root@raspberrypi:~/btcpayserver-docker#

**Comment by NicolasDorier** [comment]
The error message is bad, I just fixed it, same reason as https://github.com/btcpayserver/btcpayserver-docker/issues/241

**Comment by NicolasDorier** [comment]
I think the error in your case is that you did not checked out @Kukks  branch.

**Comment by Kukks** [comment]
This is fixed, i don't automatically add it as an additional fragment anymore
